// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.EventStoreCloud
{
    public static class GetNetwork
    {
        /// <summary>
        /// Retrieves data for an existing `Network` resource
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using EventStoreCloud = Pulumi.EventStoreCloud;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var example = Output.Create(EventStoreCloud.GetNetwork.InvokeAsync(new EventStoreCloud.GetNetworkArgs
        ///         {
        ///             Name = "Example Network",
        ///             ProjectId = @var.Project_id,
        ///         }));
        ///         this.NetworkCidr = example.Apply(example =&gt; example.CidrBlock);
        ///     }
        /// 
        ///     [Output("networkCidr")]
        ///     public Output&lt;string&gt; NetworkCidr { get; set; }
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetNetworkResult> InvokeAsync(GetNetworkArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNetworkResult>("eventstorecloud:index/getNetwork:getNetwork", args ?? new GetNetworkArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves data for an existing `Network` resource
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using EventStoreCloud = Pulumi.EventStoreCloud;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var example = Output.Create(EventStoreCloud.GetNetwork.InvokeAsync(new EventStoreCloud.GetNetworkArgs
        ///         {
        ///             Name = "Example Network",
        ///             ProjectId = @var.Project_id,
        ///         }));
        ///         this.NetworkCidr = example.Apply(example =&gt; example.CidrBlock);
        ///     }
        /// 
        ///     [Output("networkCidr")]
        ///     public Output&lt;string&gt; NetworkCidr { get; set; }
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetNetworkResult> Invoke(GetNetworkInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetNetworkResult>("eventstorecloud:index/getNetwork:getNetwork", args ?? new GetNetworkInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNetworkArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("projectId", required: true)]
        public string ProjectId { get; set; } = null!;

        public GetNetworkArgs()
        {
        }
    }

    public sealed class GetNetworkInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        public GetNetworkInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetNetworkResult
    {
        /// <summary>
        /// Address space of the network in CIDR block notation
        /// </summary>
        public readonly string CidrBlock;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string ProjectId;
        /// <summary>
        /// Provider region in which to provision the network
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// Cloud Provider in which to provision the network.
        /// </summary>
        public readonly string ResourceProvider;

        [OutputConstructor]
        private GetNetworkResult(
            string cidrBlock,

            string id,

            string name,

            string projectId,

            string region,

            string resourceProvider)
        {
            CidrBlock = cidrBlock;
            Id = id;
            Name = name;
            ProjectId = projectId;
            Region = region;
            ResourceProvider = resourceProvider;
        }
    }
}
