// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Eventstorecloud.Outputs
{

    [OutputType]
    public sealed class PeeringProviderMetadata
    {
        public readonly string? AwsPeeringLinkId;
        public readonly string? GcpNetworkId;
        public readonly string? GcpNetworkName;
        public readonly string? GcpProjectId;

        [OutputConstructor]
        private PeeringProviderMetadata(
            string? awsPeeringLinkId,

            string? gcpNetworkId,

            string? gcpNetworkName,

            string? gcpProjectId)
        {
            AwsPeeringLinkId = awsPeeringLinkId;
            GcpNetworkId = gcpNetworkId;
            GcpNetworkName = gcpNetworkName;
            GcpProjectId = gcpProjectId;
        }
    }
}
