# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'PeeringProviderMetadataArgs',
]

@pulumi.input_type
class PeeringProviderMetadataArgs:
    def __init__(__self__, *,
                 aws_peering_link_id: Optional[pulumi.Input[str]] = None,
                 gcp_network_id: Optional[pulumi.Input[str]] = None,
                 gcp_network_name: Optional[pulumi.Input[str]] = None,
                 gcp_project_id: Optional[pulumi.Input[str]] = None):
        if aws_peering_link_id is not None:
            pulumi.set(__self__, "aws_peering_link_id", aws_peering_link_id)
        if gcp_network_id is not None:
            pulumi.set(__self__, "gcp_network_id", gcp_network_id)
        if gcp_network_name is not None:
            pulumi.set(__self__, "gcp_network_name", gcp_network_name)
        if gcp_project_id is not None:
            pulumi.set(__self__, "gcp_project_id", gcp_project_id)

    @property
    @pulumi.getter(name="awsPeeringLinkId")
    def aws_peering_link_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "aws_peering_link_id")

    @aws_peering_link_id.setter
    def aws_peering_link_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "aws_peering_link_id", value)

    @property
    @pulumi.getter(name="gcpNetworkId")
    def gcp_network_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "gcp_network_id")

    @gcp_network_id.setter
    def gcp_network_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "gcp_network_id", value)

    @property
    @pulumi.getter(name="gcpNetworkName")
    def gcp_network_name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "gcp_network_name")

    @gcp_network_name.setter
    def gcp_network_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "gcp_network_name", value)

    @property
    @pulumi.getter(name="gcpProjectId")
    def gcp_project_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "gcp_project_id")

    @gcp_project_id.setter
    def gcp_project_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "gcp_project_id", value)


