// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package eventstorecloud

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PeeringProviderMetadata struct {
	AwsPeeringLinkId *string `pulumi:"awsPeeringLinkId"`
	GcpNetworkId     *string `pulumi:"gcpNetworkId"`
	GcpNetworkName   *string `pulumi:"gcpNetworkName"`
	GcpProjectId     *string `pulumi:"gcpProjectId"`
}

// PeeringProviderMetadataInput is an input type that accepts PeeringProviderMetadataArgs and PeeringProviderMetadataOutput values.
// You can construct a concrete instance of `PeeringProviderMetadataInput` via:
//
//          PeeringProviderMetadataArgs{...}
type PeeringProviderMetadataInput interface {
	pulumi.Input

	ToPeeringProviderMetadataOutput() PeeringProviderMetadataOutput
	ToPeeringProviderMetadataOutputWithContext(context.Context) PeeringProviderMetadataOutput
}

type PeeringProviderMetadataArgs struct {
	AwsPeeringLinkId pulumi.StringPtrInput `pulumi:"awsPeeringLinkId"`
	GcpNetworkId     pulumi.StringPtrInput `pulumi:"gcpNetworkId"`
	GcpNetworkName   pulumi.StringPtrInput `pulumi:"gcpNetworkName"`
	GcpProjectId     pulumi.StringPtrInput `pulumi:"gcpProjectId"`
}

func (PeeringProviderMetadataArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*PeeringProviderMetadata)(nil)).Elem()
}

func (i PeeringProviderMetadataArgs) ToPeeringProviderMetadataOutput() PeeringProviderMetadataOutput {
	return i.ToPeeringProviderMetadataOutputWithContext(context.Background())
}

func (i PeeringProviderMetadataArgs) ToPeeringProviderMetadataOutputWithContext(ctx context.Context) PeeringProviderMetadataOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeeringProviderMetadataOutput)
}

func (i PeeringProviderMetadataArgs) ToPeeringProviderMetadataPtrOutput() PeeringProviderMetadataPtrOutput {
	return i.ToPeeringProviderMetadataPtrOutputWithContext(context.Background())
}

func (i PeeringProviderMetadataArgs) ToPeeringProviderMetadataPtrOutputWithContext(ctx context.Context) PeeringProviderMetadataPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeeringProviderMetadataOutput).ToPeeringProviderMetadataPtrOutputWithContext(ctx)
}

// PeeringProviderMetadataPtrInput is an input type that accepts PeeringProviderMetadataArgs, PeeringProviderMetadataPtr and PeeringProviderMetadataPtrOutput values.
// You can construct a concrete instance of `PeeringProviderMetadataPtrInput` via:
//
//          PeeringProviderMetadataArgs{...}
//
//  or:
//
//          nil
type PeeringProviderMetadataPtrInput interface {
	pulumi.Input

	ToPeeringProviderMetadataPtrOutput() PeeringProviderMetadataPtrOutput
	ToPeeringProviderMetadataPtrOutputWithContext(context.Context) PeeringProviderMetadataPtrOutput
}

type peeringProviderMetadataPtrType PeeringProviderMetadataArgs

func PeeringProviderMetadataPtr(v *PeeringProviderMetadataArgs) PeeringProviderMetadataPtrInput {
	return (*peeringProviderMetadataPtrType)(v)
}

func (*peeringProviderMetadataPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**PeeringProviderMetadata)(nil)).Elem()
}

func (i *peeringProviderMetadataPtrType) ToPeeringProviderMetadataPtrOutput() PeeringProviderMetadataPtrOutput {
	return i.ToPeeringProviderMetadataPtrOutputWithContext(context.Background())
}

func (i *peeringProviderMetadataPtrType) ToPeeringProviderMetadataPtrOutputWithContext(ctx context.Context) PeeringProviderMetadataPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeeringProviderMetadataPtrOutput)
}

type PeeringProviderMetadataOutput struct{ *pulumi.OutputState }

func (PeeringProviderMetadataOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PeeringProviderMetadata)(nil)).Elem()
}

func (o PeeringProviderMetadataOutput) ToPeeringProviderMetadataOutput() PeeringProviderMetadataOutput {
	return o
}

func (o PeeringProviderMetadataOutput) ToPeeringProviderMetadataOutputWithContext(ctx context.Context) PeeringProviderMetadataOutput {
	return o
}

func (o PeeringProviderMetadataOutput) ToPeeringProviderMetadataPtrOutput() PeeringProviderMetadataPtrOutput {
	return o.ToPeeringProviderMetadataPtrOutputWithContext(context.Background())
}

func (o PeeringProviderMetadataOutput) ToPeeringProviderMetadataPtrOutputWithContext(ctx context.Context) PeeringProviderMetadataPtrOutput {
	return o.ApplyT(func(v PeeringProviderMetadata) *PeeringProviderMetadata {
		return &v
	}).(PeeringProviderMetadataPtrOutput)
}
func (o PeeringProviderMetadataOutput) AwsPeeringLinkId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PeeringProviderMetadata) *string { return v.AwsPeeringLinkId }).(pulumi.StringPtrOutput)
}

func (o PeeringProviderMetadataOutput) GcpNetworkId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PeeringProviderMetadata) *string { return v.GcpNetworkId }).(pulumi.StringPtrOutput)
}

func (o PeeringProviderMetadataOutput) GcpNetworkName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PeeringProviderMetadata) *string { return v.GcpNetworkName }).(pulumi.StringPtrOutput)
}

func (o PeeringProviderMetadataOutput) GcpProjectId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PeeringProviderMetadata) *string { return v.GcpProjectId }).(pulumi.StringPtrOutput)
}

type PeeringProviderMetadataPtrOutput struct{ *pulumi.OutputState }

func (PeeringProviderMetadataPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PeeringProviderMetadata)(nil)).Elem()
}

func (o PeeringProviderMetadataPtrOutput) ToPeeringProviderMetadataPtrOutput() PeeringProviderMetadataPtrOutput {
	return o
}

func (o PeeringProviderMetadataPtrOutput) ToPeeringProviderMetadataPtrOutputWithContext(ctx context.Context) PeeringProviderMetadataPtrOutput {
	return o
}

func (o PeeringProviderMetadataPtrOutput) Elem() PeeringProviderMetadataOutput {
	return o.ApplyT(func(v *PeeringProviderMetadata) PeeringProviderMetadata { return *v }).(PeeringProviderMetadataOutput)
}

func (o PeeringProviderMetadataPtrOutput) AwsPeeringLinkId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PeeringProviderMetadata) *string {
		if v == nil {
			return nil
		}
		return v.AwsPeeringLinkId
	}).(pulumi.StringPtrOutput)
}

func (o PeeringProviderMetadataPtrOutput) GcpNetworkId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PeeringProviderMetadata) *string {
		if v == nil {
			return nil
		}
		return v.GcpNetworkId
	}).(pulumi.StringPtrOutput)
}

func (o PeeringProviderMetadataPtrOutput) GcpNetworkName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PeeringProviderMetadata) *string {
		if v == nil {
			return nil
		}
		return v.GcpNetworkName
	}).(pulumi.StringPtrOutput)
}

func (o PeeringProviderMetadataPtrOutput) GcpProjectId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PeeringProviderMetadata) *string {
		if v == nil {
			return nil
		}
		return v.GcpProjectId
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(PeeringProviderMetadataOutput{})
	pulumi.RegisterOutputType(PeeringProviderMetadataPtrOutput{})
}
