// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface PeeringProviderMetadata {
    awsPeeringLinkId?: pulumi.Input<string>;
    gcpNetworkId?: pulumi.Input<string>;
    gcpNetworkName?: pulumi.Input<string>;
    gcpProjectId?: pulumi.Input<string>;
}
