// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Eventstorecloud.Inputs
{

    public sealed class PeeringProviderMetadataGetArgs : Pulumi.ResourceArgs
    {
        [Input("awsPeeringLinkId")]
        public Input<string>? AwsPeeringLinkId { get; set; }

        [Input("gcpNetworkId")]
        public Input<string>? GcpNetworkId { get; set; }

        [Input("gcpNetworkName")]
        public Input<string>? GcpNetworkName { get; set; }

        [Input("gcpProjectId")]
        public Input<string>? GcpProjectId { get; set; }

        public PeeringProviderMetadataGetArgs()
        {
        }
    }
}
