name: Pull request
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  lint:
    name: markdown lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v2
      - name: Install pulumictl
        run: curl -L https://github.com/pulumi/pulumictl/releases/download/v0.0.46/pulumictl-v0.0.46-linux-amd64.tar.gz | sudo tar zxv -C /usr/bin -f- pulumictl
      - name: Lint markdown
        run: |
          yarn install
          make lint