name: Pull request
on:
  push:
    branches:
      - '*'
jobs:
  lint:
    name: markdown lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v2
      - name: Lint markdown
        run: |
          yarn install
          make lint