name: Build and publish
on:
  push:
    tags:
      - '*'
jobs:
  build_and_deploy:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow to restore tags
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      -
        name: Install pulumictl
        run: curl -L https://github.com/pulumi/pulumictl/releases/download/v0.0.25/pulumictl-v0.0.25-linux-amd64.tar.gz | sudo tar zxv -C /usr/bin -f- pulumictl
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push NuGet package
        run: |
          dotnet nuget push nuget/**/*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}